<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <Version>0.3.0</Version>

    <RestoreAdditionalProjectSources>
      https://api.nuget.org/v3/index.json;
      https://nuget.bepinex.dev/v3/index.json
    </RestoreAdditionalProjectSources>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BepInEx.Analyzers" Version="1.0.*">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>

    <PackageReference Include="BepInEx.Core" Version="5.4.21" />

    <PackageReference
      Include="UnityEngine.Modules"
      Version="2021.3.33"
      IncludeAssets="compile"
    />

    <PackageReference Include="RiskOfRain2.GameLibs" Version="*-*" />

    <PackageReference
      Include="MMHOOK.RoR2"
      Version="*"
      NoWarn="NU1701"
    />

    <PackageReference Include="RoR2BepInExPack" Version="*" />
  </ItemGroup>

  <PropertyGroup>
    <ReleaseRoot>$(MSBuildProjectDirectory)/../../dist</ReleaseRoot>
  </PropertyGroup>

  <Target Name="PrepareModRelease" AfterTargets="Build" Condition="'$(Configuration)' == 'Release'">
    <RemoveDir Directories="$(ReleaseRoot)" />

    <MakeDir Directories="$(ReleaseRoot)/BepInEx/plugins/EclipseRandomizer" />

    <Copy
      SourceFiles="$(TargetPath)"
      DestinationFolder="$(ReleaseRoot)/BepInEx/plugins/EclipseRandomizer"
    />

    <Copy
      SourceFiles="$(MSBuildProjectDirectory)/../../manifest.json;$(MSBuildProjectDirectory)/../../README.md;$(MSBuildProjectDirectory)/../../icon.png"
      DestinationFolder="$(ReleaseRoot)"
    />
  </Target>

</Project>
